### ISSUE TITLE
parent directories with spaces don't seem to be supported

### ISSUE THREAD

**Issue by Gander7** [webpack-contrib/webpack-serve#100]
* Operating System: Windows 10 Home v1709 Build 16299.371
* Node Version: 9.11.1
* NPM Version: 5.6.0
* webpack Version: 4.4.0
* webpack-serve Version: 0.3.1

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

Duplicate issue from webpack-dev-server, difference is that having a space in the directory path with webpack-serve gives a `Not Found`  instead of a directory listing

Information and problem details found (specific to webpack-dev-server, but same issue) [here](https://stackoverflow.com/questions/49763540/webpack-webpack-dev-server-react-shows-directory-listing-when-it-should-show-app)

Found this from tracking down this [Webpack-dev-server issue](https://github.com/webpack/webpack-dev-server/issues/1375) and then trying it with webpack-serve

### Code
Not my code, but a simple starter repo I've used for testing:
https://github.com/bradtraversy/react_webpack_starter

Install and replace webpack-dev-server in `npm start` with webpack-serve

##### CLI Command
locally
`webpack-serve ./webpack.config.dev.js --open --hot` 

### Expected Behavior
App runs, works on project when there are no spaces in absolute directory path.

### Actual Behavior
Shows `Not Found` on projects where there are spaces in absolute directory path.

See github issue for more information, though it is specific to webpack-dev-server.

### How Do We Reproduce?
Used C drive to isolate issue
```
mkdir "test test" // works if the directory is testtest
cd "test test"
git clone https://github.com/bradtraversy/react_webpack_starter
cd react_webpack_starter
npm add -D webpack-serve
```
Copy `webpack.config.js` to `webpack.config.dev.js` and add `mode: 'development'`

Change `npm start` script to `webpack-serve ./webpack.config.dev.js --open --hot`

`npm start`

**Comment by shellscape** [comment]
Thanks for the issue 🍺 

webpack-serve uses [`koa-static`](https://github.com/koajs/static) for serving non-bundle static files, and [`webpack-dev-middleware`](https://github.com/webpack/webpack-dev-middleware/) for serving bundle files. This module just sets up and facilitates both of those dependencies.

Unfortunately I'm not a Windows user (and never will be again 😈 if I can help it) so I can't offer any insight into those, but I'd suggest raising this issue with one of those repos, if you can nail down the culprit. Since you saw this in `webpack-dev-server` as well, I'd wager it's an issue in `webpack-dev-middleware`. Any way it goes, it's going to require debugging and triage from a Windows user.

**Comment by JCarlosR** [comment]
I was trying to use `webpack-dev-server` and `wepback-serve` but both were not working.
After 1 strange hour, you question solved my problem (folder name with spaces).
Thanks!
