### ISSUE TITLE
Server still running when terminal is closed

### ISSUE THREAD

**Issue by SeanHub** [webpack-contrib/webpack-serve#105]
* Operating System: Windows 10
* Node Version: 8.11.1
* NPM Version: 5.6.0
* webpack version: 4.6.0
* webpack-serve Version: 0.3.1

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve
```

### Expected Behavior
To stop server and free up port when terminal is closed.

### Actual Behavior
Server is still running, therefore port is locked and allocated.

### How Do We Reproduce?
Run webpack-serve in a bash terminal and press the 'X' close button in Windows. A prompt will appear asking if you want to close the terminal. Confirm and press 'X' again. Now try and navigate to the localhost address that was created when you run webpack-serve, you will notice that the server is still running.

**Comment by shellscape** [comment]
Thanks for the issue :beer: Unfortunately this is going to be an issue with your particular environment, and the way you're terminating the running instance in your terminal emulator, rather than a bug in `webpack-serve`. We have a [slew of tests](https://github.com/webpack-contrib/webpack-serve/blob/master/test/tests/cli.js) that would fail if SIGINT termination was an issue. You should end your process using [SIGINT or SIGTERM](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html), which is usually accomplished by pressing CTL+C. This is a standard in Node.js development for long-running processes. If you don't wish to use that convention, you'll have to end the node process using Task Manager.

**Comment by SeanHub** [comment]
Thanks for the swift reply. I'd usually always use CTRL+C but I've noticed other plugins (notably [gulp-connect](https://github.com/avevlad/gulp-connect) do manage to terminate the server when the 'X' is pressed. Maybe it is out of webpack-serve's realm but are you sure it isn't code related?

**Comment by shellscape** [comment]
It's possible they might be doing something special to detect that, but how `webpack-serve` handles process exist is pretty standard. We'd happily review a PR if you find another method that covers your situation.

**Comment by SeanHub** [comment]
Understood. If I get some spare time to fiddle around with the code I'll throw a PR over. Cheers.
