### ISSUE TITLE
Recommended Practice doesnt work?

### ISSUE THREAD

**Issue by bradennapier** [webpack-contrib/webpack-serve#115]
* Operating System:
* Node Version:9.11.0
* NPM Version:
* webpack Version:4.7
* webpack-serve Version:latest any

This issue is for a:

- [x] **modification** request

### Code

Simple enough - you mention using the "serve' in the webpack config which is not allowed - it would be a good idea to say "if you use extremely old versions of webpack you can do this but you cant on Webpack 2 +

**Comment by shellscape** [comment]
@bradennapier the various sections of the issue template aren't optional, unless the template states as much. please don't ignore the issue/PR template instructions.

your assertion in the issue however, is not correct. if it were, oodles of tests would fail and there would be an army of angry open source users with pitchforks and torches posting issues to that effect. you're likely not using the package correctly in your environment. since you didn't follow the issue template, I honestly can't tell where/how you're using the package.

regardless, it's probably best for you to work from one of the test `test/fixtures/basic` configs, and if needs be, seek support using one of the options listed in the issue template, as the issues section here is not for support:

>   👉🏽 Need support, advice, or help? Don't open an issue.
  Head to StackOverflow or https://gitter.im/webpack/webpack.
