### ISSUE TITLE
It's currently not possible to specify webpacks mode

### ISSUE THREAD

**Issue by kleinph** [webpack-contrib/webpack-serve#125]
* Operating System: Linux
* Node Version: node v10.1.0
* NPM Version: npm 6.0.0
* webpack Version: webpack 4.8.1
* webpack-serve Version: webpack-serve 0.3.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve 
```

##### webpack.config.js

```js
```

### Expected Behavior
I would like to specify in which mode webpack should be started via webpack-serve.
Ideally it should default to _development_, because that's where webpack-serve will mostly be used.

### Actual Behavior
There is no option how I can specify webpack mode.

### New Feature Use Case

(Maybe also see issue #123)

**Comment by shellscape** [comment]
Opening duplicate issues is not cool. Your previous issue was closed because it's a request for support. I even linked you to the relevant documentation to solve your previous, duplicate issue. I'll paste it again here for reference:

From the issue template:

>   👉🏽 Need support, advice, or help? Don't open an issue.
  Head to StackOverflow or https://gitter.im/webpack/webpack.

_^ that means don't do what you just did - post a question in an issue seeking support. this isn't the proper place for that. you have two options there which are the proper places for support._

**Your answer lies [in the documentation](https://webpack.js.org/concepts/mode/#usage)**

**Comment by nihiluis** [comment]
i think mod author may be autistic. I dont think this can or should be discussed further

**Comment by shellscape** [comment]
@nihiluis those types of comments are not welcome anywhere in the webpack ecosystem, and absolutely not welcome in the `webpack-contrib` organization. This is your last, and only warning.
