### ISSUE TITLE
New user not sure how to make webpack-serve work

### ISSUE THREAD

**Issue by huy-nguyen** [webpack-contrib/webpack-serve#137]
* Operating System: Mac OS 10.12.6
* Node Version: 9.10.1
* NPM Version: 6.0.1
* webpack Version: 4.8.3
* webpack-serve Version: 1.0.1

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve --config webpack.config.js
```

##### webpack.config.js

See minimal repro repo [here](https://github.com/huy-nguyen/webpack-serve-bug)

### Expected Behavior
After the server has started, there's a displayed `div` that says `Hello World`. Changing the text to some other text should update the content of that `div` accordingly.

### Actual Behavior

Error message:

<img width="599" alt="screen shot 2018-05-13 at 1 29 06 am" src="https://user-images.githubusercontent.com/7352279/39964224-e5f17d5e-564d-11e8-9f62-f35fb2bccf78.png">

Am I missing something very obvious here?
### How Do We Reproduce?

- Install dependencies with `yarn`.
- Run `npm start`.
- Change the string in `src/index.js` from `Hello World` to any other string.

**Comment by shellscape** [comment]
Looks like a bug in `webpack-hot-client`. I won't have the chance to fix this for a few hours.

**Comment by shellscape** [comment]
OK the `koa-webpack` dependency needed to be bumped to the latests `webpack-hot-client`. Did that, so this is resolved in 5c32c1e. Please do choose a more descriptive issue title next time around. Something like _"Various Client Script Errors"_ so that users viewing past issues have an idea of what they're about. Thanks for reporting the error 🍺
