### ISSUE TITLE
Issue using the require flag with esm

### ISSUE THREAD

**Issue by oles** [webpack-contrib/webpack-serve#138]
This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command
`webpack-serve --require esm`

##### webpack.config.js
```js
import {resolve} from 'path'
```

### Expected Behavior
For `esm` to properly do its thing, as it's doing with `webpack-cli`

### Actual Behavior
`Unexpected token import`
<br>

I'd just like to shoot in that `webpack-serve` seems like a well made and thought out project - kudos! 
<br><br>

It was about time to check out version 4 of webpack. Fresh new project, better docs of version 4, a replacement for the old dev-server. 

Started by getting the bare project building with webpack-cli combined with esm - success! 
Next - getting webpack-serve serving... ohno. 

Started by opening an issue over at https://github.com/standard-things/esm/issues/399 before I found time to head deep into this project.

Seems like it all started over at https://github.com/webpack-contrib/webpack-serve/issues/65 where the conclusion was: 
>This module will not implement TypeScript, Babel, nor any other preprocessor support. You must feed it regular JavaScript. Note: This will not change.

So it seemed like the only way to work around this was to do something similar to: https://github.com/webpack-contrib/webpack-serve/issues/51#issuecomment-376035797
`ts-node ./node_modules/.bin/webpack-serve`
or, in my case (which is what I'm currently using)
`node -r esm ./node_modules/.bin/webpack-serve`

<br>

Then suddenly a PR adding support for it: https://github.com/webpack-contrib/webpack-serve/pull/83
and I tried using the version that got released after the PR, but neither that one works as well... 

<br>

I'm not sure if `--require` or `-r` works in other cases - I'll have time to figure out that tomorrow :+1:

**Comment by shellscape** [comment]
Thanks for the issue :beer:

I've unchecked "bug" because this isn't going to be a bug with `webpack-serve`. The module responsible for loading your config is [`webpack-contrib\config-loader`](https://github.com/webpack-contrib/config-loader), which also handles applying the module requires passed via `--require`. That changed in v1.0.0. Given that `config-loader` passes tests with [various different require hooks/preprocessors](https://github.com/webpack-contrib/config-loader/tree/master/test/fixtures/formats), this is likely going to be a problem with the `esm` require hook, if anything.

Closing for now, since it's not a `webpack-serve` issue, but feel free to continue discussion here, or open an issue with either the `esm` or `config-loader` repos (though note that the response on `config-loader` is probably going to be similar citing the passing tests).

**Comment by jdalton** [comment]
Hi @shellscape!

Do you have an example usage/config for using the `--require` option of `config-loader` with `webpack-serve`?

**Comment by shellscape** [comment]
@jdalton `--require` is basically pass-through to `config-loader`. The link above to the _hooks/preprocessors_ points to the different format fixtures, and [here are the tests](https://github.com/webpack-contrib/config-loader/blob/master/test/tests/load.js) that set the `require` option (which is what the flag does).

**Comment by jdalton** [comment]
@shellscape It looks like it's not passing it to `config-loader` and is handling it [here](https://github.com/webpack/webpack-cli/blob/next/bin/convert-argv.js#L121-L138) and [here](https://github.com/webpack/webpack-cli/blob/next/bin/config-yargs.js#L24-L32).

**Comment by jdalton** [comment]
No mixup. The feature request is to add similar functionality.
