### ISSUE TITLE
Object.defineProperty: argument is not an Object

### ISSUE THREAD

**Issue by iwazaru** [webpack-contrib/webpack-serve#164]
* Operating System: macOS 10.11.1 (host), Win 8.1 (client)
* Node Version: 8.11.1
* NPM Version: 5.6.0
* webpack Version: 4.11.0
* webpack-serve Version: 1.0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code
    import _ from 'lodash';

    function component() {
      var element = document.createElement('div');

      element.innerHTML = _.join(['Hello', 'webpack'], ' ');

      return element;
    }

    document.body.appendChild(component());

##### CLI Command

```console
  $ webpack-serve --host 0.0.0.0 --content dist --config webpack.dev.js
```

##### webpack.config.js

https://github.com/iwazaru/webpack-serve-bug/blob/master/webpack.common.js
https://github.com/iwazaru/webpack-serve-bug/blob/master/webpack.dev.js
https://github.com/iwazaru/webpack-serve-bug/blob/master/webpack.prod.js

### Expected Behavior

Web page should display "Hello webpack" and not log error in console. This is what happens in Chrome.

### Actual Behavior

In IE 11, console shows the following error and web page does not display "Hello webpack" :

    SCRIPT5007: Object.defineProperty: argument is not an Object
    File: implement.js, Line: 4, Column: 2

I can't reproduce the issue when building with webpack and serving with serve.

### How Do We Reproduce?

I forked my repo and remove all my code but the webpack & webpack serve config, and added an example from the webpack getting started guide. I can still reproduce the issue.

* `git clone https://github.com/iwazaru/webpack-serve-bug`
* `npm install && npm start`
* Browse localhost:8080 with IE 11

**Comment by shellscape** [comment]
Thanks for the issue :beer: Unfortunately this looks on the surface like a bug present in your code, rather than in `webpack-serve`. I'd highly recommend using a browser that produces proper stack traces. That would probably give you a better idea of where the error was originating.

Of note, `defineProperty` doesn't appear a single time in this repository, nor does it exist in `webpack-hot-client`. Highly recommend deep diving an issue before reporting a bug in a module. 

Also worth noting that the issues here aren't for providing support:

>   👉🏽 Need support, advice, or help? Don't open an issue.
  Head to StackOverflow or https://gitter.im/webpack/webpack.
