### ISSUE TITLE
webpack-serve does not scale to large projects

### ISSUE THREAD

**Issue by MLoughry** [webpack-contrib/webpack-serve#181]
* Operating System: Windows 10
* Node Version: 8.11.1
* NPM Version: 5.6.0
* webpack Version: 4.12.0
* webpack-serve Version: 1.0.4

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

I'm in the process of porting our project over from `webpack-dev-server-speedy` to this project, but there is a [single line](https://github.com/webpack-contrib/webpack-serve/blob/012ab602a1a745ee0570fe471324bfb50a84f3da/index.js#L41) that does not scale well. Our project is >12k modules, and the call to `stats.toJson()` is both unnecessary and costly.

### Expected Behavior
Either:
- Pass the `stats` object itself, rather than the JSON object or
- Respect the `stats` setting in the webpack config when calling `toJson()`, so consumers can specify `'errors-only'` or `'minimal'` or the like.

### Actual Behavior
`stats.toJson()` takes ~2 minutes and a significant chunk of memory to complete with every rebuild, even though the rebuild itself takes ~15-20s.

### How Do We Reproduce?
Run against a very large (>10k module) repository.

**Comment by frenzzy** [comment]
I mentioned the same problem here: https://github.com/webpack-contrib/webpack-serve/pull/157#issuecomment-393266945 but it was unanswered :disappointed:

**Comment by shellscape** [comment]
Thanks for the issue :beer:

> Pass the stats object itself, rather than the JSON object or

The stats are passed as a result of `toJson` to avoid requiring the user having to make that call several times. This is a holdover from `webpack-dev-server` (and a few other projects in the same vein). If you're curious as to the reasons why JSON is preferred over raw stats, you'll have to deep dive the git-blame on WDS and read the associated issues (not gonna write it out here in duplicate). 

> Respect the stats setting in the webpack config when calling toJson(), so consumers can specify 'errors-only' or 'minimal' or the like.

This is a misunderstanding on your part in a few ways; `webpack-serve` uses the `stats` object from the webpack compiler straight up - this means that webpack should already have it configured to use the settings from your bundle. There's nothing for webpack-server to "respect" here. It is what it is coming from webpack. And [as stated here](https://webpack.js.org/configuration/stats) the `stats` object settings in your bundle only control what information gets displayed in the default webpack reporter. So again, there's nothing for webpack-server to respect or disrespect there.

> Run against a very large (>10k module) repository.

That's not exactly a great method to state for reproduction. In the webpack ecosystem we get a lot of issues filed that are claimed to be because of a particular reason, only to find out, or have the user report back, that it's a completely different cause. For that reason we need _some method_ to reproduce this to confirm that the problem is at the source you've pointed to.

**Comment by MLoughry** [comment]
I don't have another way to reproduce the issue, but I can verify 100% that removing the call to `stats.toJson()` fixes the performance issue. This is the exact reason that @kenotron forked `webpack-dev-server` to `webpack-dev-server-speedy`, as the former had the exact same issue.

**Comment by shellscape** [comment]
_(I apologize if this seems excessive, as I know a lot of the older projects are a little more loose and shoot from the hip. We're only attempting to be really thorough and have great documentation around forward momentum. I swear we're not being nit-picky)_

Is there any way you'd be willing to put some timers around those operations, output metrics to the console, and paste or screenshot the console output? I would _really_ like to have something we can point to and say "see!" should this change create any issues down the road.

**Comment by MLoughry** [comment]
I added the following code in `index.js`, just above the existing `comp.hooks.done.tap()` call:

```js
let initialBuild = true;
let buildStartTime;
const getTimeSinceBuildStart = () => {
  let end = process.hrtime(buildStartTime);
  return `${end[0] + end[1] / 1e9}s since build-started`;
}

bus.on('build-started', () => {
  console.log(`build-started: ${initialBuild ? 'initial build' : 'rebuild'}`);
  initialBuild = false;
  buildStartTime = process.hrtime();
});
comp.hooks.done.tap('WebpackServe-PerfTest', (stats) => {
  console.log(`hooks.done: ${getTimeSinceBuildStart()}`);
});
bus.on('build-finished', () => {
  console.log(`build-finished: ${getTimeSinceBuildStart()}`);
});
```

Without the changes in #182, this was the output (after increasing the memory to 8GB; it crashed with only 4GB):
```console
build-started: initial build
ℹ ｢serve｣: Project is running at http://localhost:3000
ℹ ｢serve｣: Server URI copied to clipboard
hooks.done: 196.247953886s since build-started
build-finished: 214.212083069s since build-started
⚠ ｢wdm｣:
ℹ ｢wdm｣: Compiled with warnings.
ℹ ｢wdm｣: Compiling...
build-started: rebuild
Type checking in progress...
hooks.done: 12.173777756s since build-started
build-finished: 33.862192563s since build-started
⚠ ｢wdm｣:
ℹ ｢wdm｣: Compiled with warnings.
```

With the changes in #182:
```console
build-started: initial build
ℹ ｢serve｣: Project is running at http://localhost:3000
ℹ ｢serve｣: Server URI copied to clipboard
hooks.done: 181.480036083s since build-started
build-finished: 181.480335155s since build-started
⚠ ｢wdm｣:
ℹ ｢wdm｣: Compiled with warnings.
ℹ ｢wdm｣: Compiling...
build-started: rebuild
hooks.done: 13.629036097s since build-started
build-finished: 13.629300388s since build-started
⚠ ｢wdm｣:
ℹ ｢wdm｣: Compiled with warnings.
```

**Comment by shellscape** [comment]
Great, thanks for providing that.

**Comment by jantimon** [comment]
We had the same performance issue for the html-webpack-plugin and are removing getStats for the same reason in the next major.

**Comment by MLoughry** [comment]
@shellscape, was there a plan to release a new patch version with #182?

**Comment by kschiffer** [comment]
Thank you @shellscape !
