### ISSUE TITLE
Update to webpack-hot-client 4.x

### ISSUE THREAD

**Issue by mrfelton** [webpack-contrib/webpack-serve#185]
webpack-hot-client 4.x contains a number of improvements. See https://github.com/webpack-contrib/webpack-hot-client/releases.

Please update the dependency and documentation to leverage that.

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed portions of the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request template sections. They're in the template because they're useful to the maintainers of this project.

Also, search first. There have been a number of issues addressing this.
