### ISSUE TITLE
Feature Request: Static Url Injection

### ISSUE THREAD

**Issue by budarin** [webpack-contrib/webpack-serve#192]
* Operating System: Windows7
* Node Version: 10.4
* NPM Version: 6
* webpack Version: 4
* webpack-serve Version: -

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

### Code
in webpack-dev-server I has entry:
```js
    entry: {
        client: [
            'react-hot-loader/patch',
            `webpack-dev-server/client?${STATIC_URL}`, //inserts in resulting code right url to resources
            'webpack/hot/only-dev-server',
            './src/client/index.tsx',
        ],
    },
```
### Expected Behavior
I want to know (there is no any info about it in readme) is there such modules or configuration options like ```webpack-dev-server/client?${STATIC_URL}``` which gives an ability to inject into code the prefix with full address, pointing to current webpack-serve's location

**Comment by shellscape** [comment]
Please don't ignore Issue or Pull Request template sections. They're in the template because they're useful to the maintainers of this project.

I used to work on webpack-dev-server and I wasn't familiar with that feature, so I searched the repo just now and I couldn't find `STATIC_URL` in that repo. So I'm not sure what you're asking for. However, that looks like you're trying to modify the `entry` field of your config. `webpack-serve` doesn't support injecting or overriding any values in your webpack config file. `webpack-hot-client` takes care of automatically adding the appropriate entries to make HMR work, so if that's what you're trying to accomplish there, you don't have to add that.

**Comment by budarin** [comment]
I'm sorry - you're right.
It was from an old project code - your question got me thinking about that

**Comment by shellscape** [comment]
No worries, thanks for stopping by.
