### ISSUE TITLE
contentBase ? 

### ISSUE THREAD

**Issue by crper** [webpack-contrib/webpack-serve#197]
* Operating System: macos
* Node Version: 10.5.0
* NPM Version: 6.1.0
* webpack Version: 4.13
* webpack-serve Version:

I want use webpack-serve replace web-dev-server+web_dev-server-middleware;

but hot reload not `contentBase ` api ,  how to use  reload spect  memory output file !!!

thanks

**Comment by shellscape** [comment]
>   👉🏽 Need support, advice, or help? Don't open an issue.
  Head to StackOverflow or https://gitter.im/webpack/webpack.

Sad panda 🐼 😢  You removed portions of the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request template sections. They're in the template because they're useful to the maintainers of this project.

**Comment by crper** [comment]
OK ,Tks..
