### ISSUE TITLE
docs: Missing HMR config for React

### ISSUE THREAD

**Issue by budarin** [webpack-contrib/webpack-serve#205]
Documentation Is:

- [X] Missing
- [X] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
Since some hmr webpack's options are under internals it's not clear how to configure HMR for React.
I have switched `hot: true`. Although the changes come to the browser (I can see console log in browser) they do not modify the page.

### Your Proposal for Changes
Add some words in docs how to configure HMR for React

**Comment by shellscape** [comment]
Thanks for the issue :beer:

This project caters to more than just React, and as such we don't have documentation for each framework that it's possible to use this module with. Think about that - we'd have a million documentation files for every framework that was in use today. There was a recent tweet with a link to a blog post highlighting _32 frameworks in active use_ by a significant number of users. Documentation belongs in a project's docs, meaning that the React docs should have some info on how to use this module.

That said, `hot: true` isn't doing anything, because `true` is the default value. I would recommend reading about how to setup HMR with webpack first, and then trying webpack-serve. HMR should work identical to webpack-dev-server as well, since they both use the same module to enable that (webpack-dev-middleware).
