### ISSUE TITLE
inconvenient behavior `logTime` and `logLevel` options (maybe bug)

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/webpack-serve#237]
* Operating System: Ubuntu 18.04
* Node Version: 8.11.3
* NPM Version: 6.2.0
* webpack Version: 4.16.1
* webpack-serve Version: 2.0.2

### Expected Behavior

`logTime` option in config should setup `devMiddleware.logTime` option and `hotClient.logTime` option.

`logLevel`  option in config should setup `devMiddleware.logLevel` option and `hotClient.logLevel` option.

### Actual Behavior

Logic above does't work. 

But if i use `webpack-serve --log-level=warn` it is works (https://github.com/webpack-contrib/webpack-serve/blob/master/lib/flags.js#L73 and https://github.com/webpack-contrib/webpack-serve/blob/master/lib/flags.js#L78) 

### Code

```js

const path = require('path');

const internalIp = require('internal-ip');

module.exports = {
  entry: {
    index: [path.resolve(__dirname, 'app.js')],
  },
  mode: 'development',
  output: {
    filename: 'output.js',
  },
};

module.exports.serve = {
  content: [__dirname],
  logTime: true,
  logLevel: "warn"
};
```

### How Do We Reproduce?

Just run example above and look on output (`devMiddleware.logLevel` and `hotClient.logLevel` have `info` value).

**Comment by shellscape** [comment]
This is by design. There's another issue that raised this question (I don't have time to search for it right now). The answer is that if you are using the API or config to set log options, you must be explicit. The `--log-level` and `--log-time` command line flags are convenience flags that set everything, and operate differently.

If we were to make this change, we would again have people complaining that setting one option was setting them all (for devMiddleware and hotClient). So there's no way to please everyone. This is just how it is.
