### ISSUE TITLE
`output.publicPath` is not respected (need to use `serve.dev.publicPath` instead

### ISSUE THREAD

**Issue by EvHaus** [webpack-contrib/webpack-serve#24]
* Operating System: macOS
* Node Version: v9.6.1
* Yarn Version: v1.3.2
* webpack Version: v4.0.1
* webpack-serve Version: v0.1.5

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code

N/A

##### CLI Command

```console
  $ webpack-serve webpack.config.js
```

##### webpack.config.js

```js
{
	entry: {
		app: '/var/www/html/js/index.js',
	},
	mode: 'development',
	output: {
		path: '/var/www/html/build/',
		publicPath: './build/',
		filename: '[name].js',
	},
	serve: {
		content: '/var/www/html/build/',
		dev: {
			// Why is this needed?
			publicPath: '/build/',
		}
	},
}
```

### Expected Behavior

In the config above, note that `serve.dev.publicPath` is included. This seems to be the only way to get `webpack-serve` to serve content out of the `/build` directory, even though I have `output.publicPath` also set to `/build`.

I was expecting NOT needing the `serve.dev.publicPath` value to need to be set, but without it the web server serves the content out of `http://localhost/app.js` instead of `http://localhost/build/app.js`.

### Actual Behavior

The `output.publicPath` value of the config is not respected when running `webpack-server`.

Furthermore, the behavior of `output.publicPath` and `serve.dev.publicPath` is slightly different. The `output` value is global (so I use `./build`), but the `serve` value is relative, so I have to use `/build` (note the lack of initial dot).

This was highly unexpected when migrating from `webpack-dev-server` to `webpack-serve` and I ended up losing quite a lot of time during the migration. If this is behavior is as-designed, would it be possible to explicitly describe this in the docs so other people who run into this aren't as surprised?

### How Do We Reproduce?

See config code above to reproduce.

**Comment by EvHaus** [comment]
I found this doc section: https://webpack.js.org/configuration/dev-server/#devserver-publicpath-

And after reading that, I think I have a better understanding on why it works the way it does. However, it still wasn't super clear what was happening and I wonder if there is some way for `webpack-serve` to be more dev-friendly to this respect.

Would it maybe be make sense to send a warning to the console? Something along the lines of `You have an "output.publicPath" value configured, but no "serve.dev.publicPath" is set. Bundle output will be served from "/".`

**Comment by shellscape** [comment]
Thanks for the isssue 🍺 

This is an unfortunate upstream problem with [`webpack-dev-middleware`](https://github.com/webpack/webpack-dev-middleware). The `serve.dev` option is a pass-through to `webpack-dev-middleware` so it's not so much an issue of `webpack-serve` deviating, since WDM handles all the requests to bundled files. `webpack-dev-server` may do something to munge that to make it work as you've outlined - but in that case sounds more like a hack than fixing the root cause of the problem. I'd suggest migrating this issue over to WDM's repo instead.

WDM's docs state that the two publicPaths should be identical. https://github.com/webpack/webpack-dev-middleware#publicpath. And according to the webpack docs for using middleware it should work if they're identical. So it sounds like there's something amiss there.

**Comment by shellscape** [comment]
FWIW webpack-dev-middleware should probably use the compiler's `option.publicPath` if none is specified explicitly. `webpack-serve` should probably not default that to `/` without inspecting the webpack config for that property first.

**Comment by shellscape** [comment]
@EvHaus I took a look at WDM today. If you repost this issue in `webpack-dev-middleware`, I can share more information with you. It's not pertinent to `webpack-serve`.

**Comment by EvHaus** [comment]
Logged here: https://github.com/webpack/webpack-dev-middleware/issues/269
