### ISSUE TITLE
Garbage characters output on windows command prompt

### ISSUE THREAD

**Issue by pdeva** [webpack-contrib/webpack-serve#244]
* Operating System: Windows 10
* Node Version: 10
* NPM Version: Yarn 1.7.0
* webpack Version: 4.16.1
* webpack-serve Version: 2.0.2

### Expected Behavior
No garbled characters in the console output

### Actual Behavior
Screenshot
![image](https://user-images.githubusercontent.com/3190176/43102048-e88fe1e0-8e7e-11e8-8ff1-736aab2d2305.png)

### Code

```js
  // webpack.config.js
  // If your bitchin' code blocks are over 20 lines, please paste a link to a gist
  // (https://gist.github.com).
```

```js
  // additional code, HEY YO remove this block if you don't need it
```

### How Do We Reproduce?

Write the most minimal webpack config file and launch webpack-server in a windows 10 command prompt window

**Comment by shellscape** [comment]
Bummer. Those aren't "garbage" characters. Those are characters representing the fact that the font doesn't contain a character. Looks like you're using a font that doesn't have very good unicode support. I'd recommend changing your font to something more modern.

**Comment by pdeva** [comment]
the font being used is 'Consolas', the most popular programming font and one that comes standard with windows.

**Comment by shellscape** [comment]
sorry, but the issue is going to be on your end with your console or system. consolas supports the characters the log uses without doubt - you can verify that by using a font browser to verify the [characters used](https://github.com/webpack-contrib/webpack-log/blob/master/index.js#L24) are valid. Unfortunately the onus is on you to find the cause and solution.
