### ISSUE TITLE
CLI errors aren't shown until you Ctrl+C the server

### ISSUE THREAD

**Issue by EvHaus** [webpack-contrib/webpack-serve#25]
* Operating System: macOS
* Node Version: v9.6.1
* Yarn Version: v1.3.2
* webpack Version: v4.0.1
* webpack-serve Version: v0.1.5

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve webpack.config.js
```

##### webpack.config.js

Any invalid config can be used to reproduce the issue. In the example below I have an invalid value set for `serve.hot.server`.

```js
{
	entry: {
		app: '/var/www/html/js/index.js',
	},
	mode: 'development',
	serve: {
		hot: {
			server: 'this-is-not-a-real-thing',
		}
	},
}
```
### Expected Behavior

The `webpack-serve` CLI command should stop and print an error message.

### Actual Behavior

The `webpack-serve` command hangs infinitely until the user presses Ctrl+C in the terminal to kill it. And only then, do you see the error:

```
TypeError: server.on is not a function
    at addListeners (/Users/ev.haus/Git/ux/node_modules/ws/lib/websocket-server.js:310:48)
    at new WebSocketServer (/Users/ev.haus/Git/ux/node_modules/ws/lib/websocket-server.js:77:31)
    at module.exports (/Users/ev.haus/Git/ux/node_modules/webpack-hot-client/index.js:35:15)
    at fn (/Users/ev.haus/Git/ux/node_modules/koa-webpack/index.js:74:18)
    at middleware.webpack.state.getPort.then (/Users/ev.haus/Git/ux/node_modules/webpack-serve/lib/server.js:32:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:705:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:665:3
```

### How Do We Reproduce?

- Create an invalid config file (or use the one above)
- Start the `webpack-serve` server via `webpack-serve webpack.config.js`
- Note that the server prints a `｢serve｣: Project is running at` but just hangs there forever
- Press Ctrl+C to kill the CLI
- Error message will be printed.

**Comment by shellscape** [comment]
Thanks for the issue 🍺 

As wonky as it probably sounds, that's a feature to expose unhandled exceptions in `Promises` using https://github.com/sindresorhus/loud-rejection. We chose not to use `hard-rejection` as some exceptions might call for doing something more while the server is running, even in an in-error state. 

The root cause of this one is koa-webpack > webpack-hot-client throwing and the rejected promise not being handled in webpack-serve. I'm presently working on a new minor version with a slew of fixes for the final release of webpack v4, and I'll put this fix in that branch.
