### ISSUE TITLE
Hot Module Replacement only works every other time otherwise the page completely reloads or does nothing at all

### ISSUE THREAD

**Issue by NearAutomata** [webpack-contrib/webpack-serve#254]
In an effort to fix a really odd issue wherein HMR would only work occasionally I tried `webpack-serve` instead of `webpack-dev-server` to rule out problems. Unfortunately the same problems occur with `webpack-serve` and I wanted to make you aware of it, in the hopes of a quick location and resolution of this bug.

The original issue can be seen here: https://github.com/webpack/webpack/issues/7814

---

* Operating System: Windows 10 Build 1803
* Node Version: 10.7.0
* NPM Version: yarn 1.9.2
* webpack Version: 4.16.3
* webpack-serve Version: 2.0.2

### Expected Behavior
I expect the HMR every time and no page reload at all.

### Actual Behavior
Hot Module Replacement works every other time but not all of the time. A more detailed explanation (even though not yet stripped) with pictures is [available here](https://stackoverflow.com/q/51594983/796036).

### Code
A stripped down (kinda MWE) version can be found here: https://github.com/NearAutomata/redux-hmr-issue

*I removed almost everything, even the second renderer process and `electron-redux` link and the error is still occuring, so it is an HMR issue.*

Clone and run the following commands:

    yarn
    yarn run build-main
    yarn run build-renderer-hot

And in a second terminal run

    yarn run start-hot

**Comment by shellscape** [comment]
If this issue is reproducible with both webpack-serve _and_ webpack-dev-server, then this was not the appropriate place to open an issue. It's almost entirely certain that it's either your config, app structure, or webpack proper at fault (those tend to be most common). webpack-serve uses different mechanisms for HMR detection, reload than does webpack-dev-server. The only commonality between it and webpack-serve is that both use webpack's provided `HotModuleReplacementPlugin`. I don't believe that opening an issue here was necessary, so I'd recommend closing this one until you work through https://github.com/webpack/webpack/issues/7814 properly, and re-open it if there's fault found in this module.

It's also of note that webpack-serve doesn't really deal with HMR at all, and that HMR is handled nearly in full by webpack-hot-client.

**Comment by NearAutomata** [comment]
Fair enough, just wanted to give it a try hoping you might possibly have stumbled upon such an erratic behavior. I'll be waiting to see whether someone can help me over at the webpack repo.

**Comment by shellscape** [comment]
Please do reopen (or create an issue on webpack-hot-client) if it's determined to be a problem here. Given the wonky nature of what you're seeing, some direction as to the culprit is always welcomed.
