### ISSUE TITLE
command line arguments passed via --env do not work

### ISSUE THREAD

**Issue by jacek213** [webpack-contrib/webpack-serve#263]
* Operating System: Ubuntu 18.04
* Node Version: 8
* webpack Version: 4.16.2
* webpack-serve Version: 2.0.2

### Expected Behavior

`env` parameters should be respected and passed to webpack config.

### Actual Behavior

`webpack-serve ./conf.js --env.apiUrl=example.com` throws:

    Error: Flags were specified that were not recognized:

      --env  Not sure what you mean there

**Comment by ppluchon** [comment]
Hello jacek213, 
Did you find any workaround?

Thanks

**Comment by xavierfoucrier** [comment]
Hi,

I had a similar issue last month: if you are using `webpack-command` in your dependencies you will get this error because **the new CLI is lightweight** and doesn't contain all features of the "old" `webpack-cli`.

You will get more informations on the official repository: https://github.com/webpack-contrib/webpack-command#differences-with-webpack-cli.

In my case, I have **splitted my configuration** into multiple files and I am using **npm scripts** to target the file I need, like: `"build:dev": "webpack --config webpack.dev.js"`. This is a good choice since the `webpack-command` allow you to **extend** any webpack configuration.

Hope this help. :wink:

**Comment by alexander-akait** [comment]
Please don't use `webpack-command` (it is experemental repo) and will be deprecated and archived in near future in favor `webpack-cli` (all features will be migrated).

**Comment by xavierfoucrier** [comment]
This is a very interesting and useful information, I didn't know that...
Why ? The `webpack-command` don't do the job properly?

Thanks for sharing :+1:

**Comment by alexander-akait** [comment]
@xavierfoucrier Two CLIs are misleading developers, we union this package in one - `webpack-cli`.

**Comment by jacek213** [comment]
@ppluchon as a workaround, I'm using regular `ENV` variables in conjunction with `DefinePlugin`.

    // webpack config
    function readENV(key) {
      const val = process.env[key]
      return val && val.length ? val : undefined
    }

    const API_URL = readENV("API_URL") || SOME_DEFAULT_API_URL

    return new webpack.DefinePlugin({
      __API_URL__: JSON.stringify(API_URL),
    })

    // package.json
    "start:local": "API_URL=http://localhost:3000 yarn start"

**Comment by ppluchon** [comment]
Thanks to all of you, it was really helpful !

**Comment by xavierfoucrier** [comment]
@evilebottnawi Thanks for the clarification. I totally agree with you. When I started to learn webpack, some developers of the community told me to work with `webpack-command` instead of `webpack-cli`. If the finality is to have one CLI and merge all webpack-command features into `webpack-cli`, I will use it for future developments. Thanks again :+1:

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
