### ISSUE TITLE
webpack-serve-overlay

### ISSUE THREAD

**Issue by shellscape** [webpack-contrib/webpack-serve#4]
The `overlay` functionality of webpack-dev-server has been removed as a built-in feature of `webpack-serve` in moving towards the add-on philosophy. As such, a module is needed to provide the necessary supporting files, and an example of wiring up the add-on, to provide the same functionality in a separated concern.

**Comment by shellscape** [comment]
Closing in favor of https://github.com/webpack-contrib/webpack-client-overlay/issues/1

**Comment by G-Rath** [comment]
@shellscape that link 404s. Has the repo been moved or deleted in favor of something else?

**Comment by shellscape** [comment]
@G-Rath nothing has been released so you're not missing out on anything. afaik there hasn't yet been development on an overlay for webpack-serve

**Comment by G-Rath** [comment]
@shellscape I have created & published [`webpack-serve-overlay`](https://github.com/G-Rath/webpack-serve-overlay) that uses the overlay from `webpack-dev-server` to do this.

It's got none of the magical features that surrounding webpack packages have, because I threw it together quickly - I'm keen to dive into the webpack ecosystem, but don't really have much time to sit down and dedicate to learning everything right now, in order to attempt some of the things you mentioned in [this issue](https://github.com/webpack-contrib/webpack-hot-client/issues/19).

For the time being it works exactly as it did when it was in `webpack-dev-server`.

I welcome any and all input you're willing to provide on it. I've made two issues on the repo already that detail the main two things I'd like to see added to the package.

I'm hoping that for now it'll serve as a decent stand-in, and launching platform for the overlay :)

**Comment by shellscape** [comment]
🤩that's great! Would you like me to add that to the third party add-ons in the README?

**Comment by G-Rath** [comment]
@shellscape Sure, but hold off for now: For some reason it's breaking hot reload refresh.

This is what a normal hot-reload looks like in the console:

<img width="677" alt="ss 2018-06-30 at 12 12 48" src="https://user-images.githubusercontent.com/3151613/42119390-35a8a5b6-7c5f-11e8-9fc9-910a82341e69.png">

But with the overlay:

<img width="420" alt="ss 2018-06-30 at 12 14 38" src="https://user-images.githubusercontent.com/3151613/42119393-3f3ee270-7c5f-11e8-9815-faacf3ead772.png">

I suspect this is b/c the client has a try/catch that is only for the bundle entry...?

It feels to me that the overlay isn't being 'registered' somewhere where it should be, so it's not being picked up.

**Comment by G-Rath** [comment]
I've created [#5](https://github.com/G-Rath/webpack-serve-overlay/issues/5) for this.

**Comment by G-Rath** [comment]
@shellscape I found that you can import the overlay instead of including it as an entry, and it'll work fine.

I've updated the README to recommend this instead, and released it as a bug version.

I'm happy to have this included in the README section now :)

(Also this doesn't actually use the 'add-on' feature: I initially looked into it, but then realised that since `webpack-serve` already sends error messages to the client socket, I didn't actually need to do anything webpack-build-side).

**Comment by shellscape** [comment]
@G-Rath wonderful! I'll get it in there soon. (I'll be gone most of tomorrow)

Brilliant idea about simply importing it into the bundle btw. 

Off-topic question: Do you have a twitter account?

**Comment by G-Rath** [comment]
@shellscape Thank you - It should solve a lot of problems.

I do technically have a [a Twitter](https://twitter.com/grathjones), but I never use it XD

**Comment by maximandrewz** [comment]
@shellscape @G-Rath Hi guys. I was studying this issue in February. So I found out that Facebook guys re-wrote hot client completely and we’re injecting it as an entry point instead of original hot client for a reason.

Error overlay gets initialised automatically. But when the error is fixed, especially when error happened in a browser rather then during compilation, after HMR replaced fixed module it should trigger method to clear the error overlay.

Therefore, error overlay can’t be integrated easily.

See Facebook WebpackHotDevClient code:
[After successful hot chunk application](https://github.com/facebook/create-react-app/blob/ea7b37414aa887dfe7722bbc1c85b3291083053a/packages/react-dev-utils/webpackHotDevClient.js#L109)
and [after warnings displayed](https://github.com/facebook/create-react-app/blob/ea7b37414aa887dfe7722bbc1c85b3291083053a/packages/react-dev-utils/webpackHotDevClient.js#L151)

Therefore, either you should hardcode it or call custom callback(s) provided through config or other way.

**Comment by shellscape** [comment]
@maximandrewz I have absolutely no idea what you're trying to convey. If you're attempting to report an issue with `webpack-serve-overlay`, a third-party module, you should do so [on its repo](https://github.com/G-Rath/webpack-serve-overlay). CRA also doesn't use `webpack-serve` - they use `webpack-dev-server`, so I'm not even sure why you're here instead of poking at [`webpack-dev-server`](https://github.com/webpack/webpack-dev-server).

The comment at the top of the file you linked to also states:

```js
// This alternative WebpackDevServer combines the functionality of:
// https://github.com/webpack/webpack-dev-server/blob/webpack-1/client/index.js
// https://github.com/webpack/webpack/blob/webpack-1/hot/dev-server.js
```

so yeah. I think you're in the wrong place.

**Comment by maximandrewz** [comment]
@shellscape I'm trying to convey that integrating Error Overlay into `webpack-serve` will not going to be easy task.

I pointed you into two things which will be obstacles on your path.

As I said, integrating `Error Overlay` into `webpack-dev-server` Facebook completely re-wrote `hot-client` and were injecting it through `entrypoint` (here)[https://github.com/facebook/create-react-app/blob/ea7b37414aa887dfe7722bbc1c85b3291083053a/packages/react-scripts/config/webpack.config.dev.js#L56] instead of (original HMR)[https://github.com/facebook/create-react-app/blob/ea7b37414aa887dfe7722bbc1c85b3291083053a/packages/react-scripts/config/webpack.config.dev.js#L55]

I understood that this is the right place to post useful info about integrating `Error Overlay` into `webpack-serve` as I can see you discuss it above.

**Comment by shellscape** [comment]
This project has very little in common with `webpack-dev-server` and doesn't share those limitations. `webpack-hot-client` is used to avoid the issues in `webpack-dev-server`, so while I get now what you were trying to share, it's already moot.

We already have a functional overlay thanks to @G-Rath in https://github.com/G-Rath/webpack-serve-overlay

**Comment by maximandrewz** [comment]
As stated in `webpack-serve` [README.md](https://github.com/webpack-contrib/webpack-serve#community-add-ons) it is a community add-on.

Also, it is too lightweight and not going to work properly when error occurs in the browser rather then during `compilation` or `lint` stage at the server side.

By `too lightweight` I mean that it:
- produces the same output you have in your console instead of pointing in the line and character exactly where you have an error as Facebook overlay does;
- it has no functionality to open your editor when clicked on the link in the browser, which is a great feature too.

To have all of it you will have to do something similar as Facebook did. They hardcoded overlay in their own `hot-client` for a reason.

**Comment by shellscape** [comment]
`webpack-serve-overlay` is sufficient for now.

A third-party or community add-on is no less valid. The way you are phrasing your messages is reading as slightly insulting to @G-Rath 's work, and that's not cool. An overlay will not be built-in to `webpack-serve` nor `webpack-hot-client`, regardless of what you believe the reasons that "facebook" were. This is not create-react-app, this is not facebook. You can work to help @G-Rath  improve `webpack-serve-overlay`, or you can write your own. But please, stop asserting that we need to model our approach after facebook.

**Comment by maximandrewz** [comment]
I’m so sorry that you perceive my good minded propositions as insults.

I was criticising solution which is normal part of software engineering process to achieve the best result.
I have never criticised him personally.

I was hoping that you as open-source engineers are looking to create the best tools and experiences for other software engineers. At least this is my perception of open-source software as collaborative effort. But if you have here invisible war just to be cooler than others, then sorry, I withdraw.
