### ISSUE TITLE
Can't disable hot module reload in config

### ISSUE THREAD

**Issue by iMarv** [webpack-contrib/webpack-serve#48]
* Operating System: Ubuntu 17.10
* Node Version: v9.6.1
* NPM Version: v5.7.1
* webpack Version: 4.1.0
* webpack-serve Version: 0.2.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve
```

##### serve.config.js

```js
module.exports = {
    content: '/',
    port: 4200,
    hot: {
        hot: false,
    },
    add: (app, middleware, options) => {
        app.use(convert(history()));
    },
};

```

### Expected Behavior
`hot` property contains options object for `webpack-hot-client` which has the proeprty `hot` which, if set to false, does not invoke hot module reload.

### Actual Behavior
Hot module reload is still active and websocket client keeps connecting

### How Do We Reproduce?
Toggle `hot` option between true and false and see no changes in execution

**Comment by shellscape** [comment]
Thanks for the issue 🍺  Unfortunately this should have been reported on [`webpack-hot-client`](https://github.com/webpack-contrib/webpack-hot-client), though I believe your issue is the same as the issue that PR https://github.com/webpack-contrib/webpack-hot-client/pull/28 was created for. Please head to that project.
