### ISSUE TITLE
Hot reloading doesn't work when a local production build exists?

### ISSUE THREAD

**Issue by shongololo** [webpack-contrib/webpack-serve#54]
* Operating System: Mac 10.13.3
* Node Version: 9.7.1
* NPM Version: Yarn 1.5.1
* webpack Version: 4.1.1
* webpack-serve Version:  0.2.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve
```
### Actual Behavior
When a local production build exists at `./dist` then `webpack-serve` will serve this static content instead of the hot-reloading app content.

### Expected Behavior
When modifying the code for hot-loading to update the browser running the webpack serve instance.

### How Do We Reproduce?
Build your app locally, e.g. `yarn run build`, then run `webpack-serve` and make modifications to the app to test hot reloading.

**Comment by shellscape** [comment]
Thanks for the issue :beer: That's definitely not something that's typical, and we have tests that run around that stuff to make sure it works. It's a bummer that you removed the section for your webpack config. Can't help you because of that. Issue templates are there for a good reason. If you can find a cause or would like to add more information to your issue, perhaps someone can help you.

**Comment by shongololo** [comment]
The issue was that the webpack-serve config had the same content location as the manual build location which is what was causing the issue. Closing.

**Comment by rubencodes** [comment]
Having the same issue here—I'm sure it's something with my config—but `webpack-serve` seems to be looking to serve files in my `/dist` folder (i,e. my `output`) when my `entry.app` is set to `src/index.jsx`.

My `webpack.config.js` looks (approximately) like this:

```
module.exports = {
    entry: {
        app: ['./src/index.jsx']
    },
    {
        path: path.join(__dirname, '/'),
        publicPath: '/',
        filename: 'dist/bundle.[name].js',
        chunkFilename: 'dist/chunk.[name].js'
    },
    serve: {
        add: (app) => app.use(convert(history())),
        content: path.join(__dirname, '/'),
        port: 4000,
        open: true
    }
}
```

I'm probably missing something obvious with the `content` field...

**Comment by shellscape** [comment]
@rubencodes hm that's the basic setup most of our tests use. you can try omitting `content` and it'll use the `context` from webpack. Or you can try specifying a `context` property in your config that uses `path.resolve(__dirname)`. they're all pretty synonymous.

**Comment by rubencodes** [comment]
@shellscape Ah, I see what you mean. If that's the case, `webpack-serve` is certainly *looking* for the right files, it's just not actually building anything, so it's coming up with 404's. Got to the bottom of it I think, was just because webpack itself wasn't compiling due to an outdated plugin. Once I fixed those issues, `webpack-serve` was able to resolve all the right files! 🎉 Would be nice if those errors had been surfaced some other way :)

**Comment by shellscape** [comment]
Did you see any error output in the console? If not, you can try passing `dev: { logLevel: 'trace' }`, but I'm pretty sure it defaults to `info` which should have shown errors. You can also try using `webpack-stylish`, it has much better formatting for errors and such.

**Comment by shellscape** [comment]
@rubencodes as of 4.x you should be explicit about what's actually running webpack (it can be confusing). I'm guessing you mean `webpack-cli` when saying "webpack on its own." And in that event, if there is output using the CLI that doesn't exist in this environment, that needs to be resolved. I'd highly recommend opening an issue on `webpack-dev-middleware` with a config that'll reproduce that condition so that can be fixed up there.

**Comment by rubencodes** [comment]
@shellscape Apologies for the confusion—I mean running the `webpack` command itself in the command line, yes. I'll try reproducing and opening an issue there, thanks!

**Comment by shellscape** [comment]
Just so we're on the same page, that issue should go on `webpack-dev-middleware`.

```console
$ webpack ...
```

Is run by `webpack-cli` now, which is a separate module/repo too.

**Comment by rubencodes** [comment]
@shellscape Apologies, this has been sort of a "one step forward, two steps back" situation 😅
- I'm able to compile with `webpack-cli`'s `webpack` command now, successfully.
- When I run `webpack-serve`, I'm getting a "[wdm]: Compiled successfully." message at the bottom.

However, when I localhost opens up (automatically due to the `open: true` setting) I'm back to getting 404 Not Found messages regarding files in my `/dist` folder. I turned on `dev: { logLevel: 'trace' }` but I'm not seeing any error messages or anything fishy beyond the 404's.

<img width="965" alt="screen shot 2018-03-19 at 12 55 23 pm" src="https://user-images.githubusercontent.com/1036549/37610025-f71db4ac-2b74-11e8-90bb-61e0903848c5.png">
<img width="1278" alt="screen shot 2018-03-19 at 12 55 58 pm" src="https://user-images.githubusercontent.com/1036549/37610036-fc28141a-2b74-11e8-8083-097b76860a75.png">
<img width="1439" alt="screen shot 2018-03-19 at 12 57 58 pm" src="https://user-images.githubusercontent.com/1036549/37610128-3014cfc0-2b75-11e8-91ee-d618cc5a6694.png">
<img width="575" alt="screen shot 2018-03-19 at 12 58 43 pm" src="https://user-images.githubusercontent.com/1036549/37610165-4a6ee400-2b75-11e8-87d5-3df6308461bd.png">

Any ideas how I might debug further?

**Comment by shellscape** [comment]
You're pretty far off track from the original issue now. I'd suggest creating a new issue, but you'll need to provide a _minimal viable repo_ that will reproduce the issue. Most of the time this kind of thing is a config problem.

**Comment by rubencodes** [comment]
Apologies—reason I kept it here is because I am still having the original issue—if the production build is in my `/dist` folder, it seems to use that instead (i.e. it doesn't 404). Not sure if that's a red herring...Happy to open a new issue!

**Comment by rubencodes** [comment]
UPDATE: I feel silly now. Looks like the issue was I removed the `entry` field from the webpack.config.js. While `webpack-cli` is fine with this and correctly defaults, I'm guessing some other module (maybe `webpack-serve` or something else) is not fine with that. Adding it back in fixed my issue. Figured this out while trying to create a minimal viable repo, so happy to post it in a new issue if that's desired?

**Comment by benwiley4000** [comment]
@shellscape I am experiencing the same problem. You can see my webpack config [here](https://github.com/benwiley4000/react-responsive-audio-player/blob/next/webpack.config.js), if that's helpful.

When a production build is already built at `/dist`:
* There is no hot reloading
* The bundle served is actually the production build, not the dev server build.

This is surprising and inconsistent behavior for someone moving from webpack-dev-server (me!). webpack-dev-server always serves from a virtual file system and doesn't even attempt to read from the real file system (as far as my experience using it has ever been). I would prefer ***not*** to have to delete my production build every time I run the dev server. :slightly_smiling_face: 

As written by @shongololo:

> The issue was that the webpack-serve config had the same content location as the manual build location

Being able to use the same content location as my production build is behavior I rely on, since I use the same static HTML file to test both my development and production builds. It would be a great improvement to support this setup. I would imagine that use case is much more common than wanting to serve a stale production build via webpack-serve. :smiley:

**Comment by shellscape** [comment]
> This is surprising and inconsistent behavior for someone moving from webpack-dev-server

The first thing to note is that ` webpack-serve` is not the giant bloated mess that is `webpack-dev-server` and parity with that module is not webpack-serve's goal.

> webpack-dev-server always serves from a virtual file system and doesn't even attempt to read from the real file system

WDS uses webpack-dev-middleware, as does webpack-serve, and that's the module reading from the virutal file system. aside from that your assumption here is incorrect. I could point you at several places in code that show that, but it's easy to glean/search.

I'm really not sure what setup you're aiming for here, but doesn't sound like the typical development test route. You've got some contradictory language in there about your existing production build that's a little confusing. My guess is that you're making use of some of quirks of webpack-dev-server (of which there are many) to pull off your build. webpack-serve doesn't do anything special with the `content` or `dev` options. It'll serve anything from `content` as static content, and it'll pass the `dev` options straight onto webpack-dev-middleware. The intent of webpack-dev-middleware, and of leveraging that module, is that it handles the build and the build in "virtual file system" aka. `MemoryFileSystem`, AND all requests to the `MemoryFileSystem`. (webpack-serve is BIG on separation of concerns, and that's what will prevent the same issues from befalling the module as did webpack-dev-server.) webpack-serve doesn't actually handle any of that itself.

You might want to source dive webpack-dev-server to see how (possibly why, with the blame feature on Github - that would be useful) it goes about satisfying your development scenario. And then once that's discovered, if you'd like to, I'd suggest opening a separate issue to discuss the merits of that.

**Comment by rubencodes** [comment]
Just wanted to say @benwiley4000 that I had the same issue with it reading my prod build from the filesystem instead of anything virtual, which would break hot reloading whenever I compiled for prod. 

Turned out `webpack-serve` was reading `index.html` from my project root directory, which points to my prod build. I moved the `index.html` file into a different folder and voila, all was good. Couldnt figure out how to change where `webpack-serve` grabbed its virtual `index.html` from without screwing up other parts of my setup. Wish it hadnt preferred the filesystem’s hard copy in the first place, but what’re you gonna do.

**Comment by shellscape** [comment]
@rubencodes you could always try switching the order in which middleware is applied by using `add` https://github.com/webpack-contrib/webpack-serve#add-function-parameters. That may give you the case you're looking for.

**Comment by benwiley4000** [comment]
@rubencodes:
> Wish it hadnt preferred the filesystem’s hard copy in the first place, but what’re you gonna do.

Agreed! :wink:

@shellscape:
> I'm really not sure what setup you're aiming for here, but doesn't sound like the typical development test route. You've got some contradictory language in there about your existing production build that's a little confusing.

Could you clarify what language is contradictory? To be clear when I say "test" I mean "eyeball test" not unit testing (it's a React component library). I don't have reason to think my setup is particularly uncommon, but perhaps it is! I will say it sounds just like what @rubencodes had.

@shellscape:
> You might want to source dive webpack-dev-server to see how (possibly why, with the blame feature on Github - that would be useful) it goes about satisfying your development scenario.

Good idea! It's great to know this is a webpack-dev-middleware thing, and not something implemented directly here. I'll try to see what I can find. Thanks! :relaxed: 

BTW, I understand feature parity with WDS is not a goal, though when folks visit the GitHub page for WDS they are told that project is basically dead and we should all use this one instead. So for the sake of flexibility with existing setups it can be useful to have clear transition paths documented. :slightly_smiling:

**Comment by shellscape** [comment]
> Good idea! It's great to know this is a webpack-dev-middleware thing, and not something implemented directly here. I'll try to see what I can find. Thanks! 

Yeah no problem. I'm all about finding a way to make things "just work." If you can do some dirty work and get to the bottom of it, we'll see what we can do here (or elsewhere) to accommodate your scenario.
