### ISSUE TITLE
Unable to use default-exported Webpack Config

### ISSUE THREAD

**Issue by WorldMaker** [webpack-contrib/webpack-serve#57]
* Operating System: Windows 10
* Node Version: v6.11.3
* NPM Version: 5.7.1
* webpack Version: 4.1.1
* webpack-serve Version: 0.2.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve --config .\webpack.config.js # remove this block if using the API
```

##### webpack.config.js

```ts
 export default myWebpackConfig
```

```js
  exports.default = myWebpackConfig
```

### Expected Behavior

My `.\webpack.config.js` uses a default export (ESM-style, though currently output as a commonjs module with an `exports.default`. This works fine in Webpack and has for several versions. It was suggested to try `webpack-serve` over `webpack-dev-server` and I expected it to load my config file just as Webpack and `webpack-dev-server` do.

### Actual Behavior

An error is produced by Webpack, when called by `webpack-serve`, that it is getting an object with only an entry `default`, rather than a webpack config.

### How Do We Reproduce?

In a CommonJS webpack config change `exports = myWebpackConfig` to `exports.default = myWebpackConfig`.

The upstream issue in the config loader appears to be davidtheclark/cosmiconfig#109.

**Comment by shellscape** [comment]
Thanks for the issue 🍺  Since Node v9 doesn't support ESM without a harmony flag (https://nodejs.org/api/esm.html) this isn't something that I'm going to feel obligated to support directly. If webpack proper has special sugar to allow for that style export, that's awesome. But until it drops in a Node release without a flag, it's not something I'm interested in supporting.

You've identified the upstream issue (nice sleuthing) so we're going to close this one.
