### ISSUE TITLE
es6 'import' breaks webpack-serve

### ISSUE THREAD

**Issue by kobeaerts** [webpack-contrib/webpack-serve#81]
* Operating System: OS X High Sierra
* Node Version: Latest
* NPM Version: Latest
* webpack Version: 4
* webpack-serve Version: 0.3.0

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve --config ./webpack-config/dev.babel.js
```

##### webpack.config.js

https://github.com/kobeaerts/packed

```js
import path from 'path';

import StylelintPlugin from 'stylelint-webpack-plugin';
import Autoprefixer from 'autoprefixer';

import common from './common.babel.js';
....
```

### Expected Behavior

Uhm work ahha :D 

### Actual Behavior

```
(function (exports, require, module, __filename, __dirname) { import path from 'path';
                                                              ^^^^^^

SyntaxError: Unexpected token import
```

### New Feature Use Case

Is it possible to make it working with import syntax?

**Comment by shellscape** [comment]
@kobeaerts thanks for filling out the issue template 🍺 

Careful with that `bug` checkbox - bugs are for problems with existing functionality. You'll have to compile your bundle appropriately for your target environment. `webpack-serve` has no magic baked into to compile configs for you. And that's not something the module will be getting into the business of. You can however, use modules like `@babel/register` if you need runtime babel support rather than compiling down to ES that Node understands in the version you're using.

**Comment by catamphetamine** [comment]
@shellscape 
> You can however, use modules like @babel/register if you need runtime babel support rather than compiling down to ES that Node understands in the version you're using.

Yeah, that means having two webpack configs instead of one: one for the actual config and another one a "babel-register" stub so it's really inconvenient for users of this library.

**Comment by catamphetamine** [comment]
@shellscape And if I do `--require babel-register` then it throws an error `configuration has an unknown property 'default'` because you don't check internally for ES6 modules which have `.default` export instead of just `require('..')`

**Comment by shellscape** [comment]
@catamphetamine there's a super useful button labeled _"Edit"_ that appears when you click the three magical dots on the top right of a reply. Use that next time. 

> because you don't

correction: because the module doesn't. I am not out to get you. I am someone who tosses free time at a community-driven project.

Folks are really used to webpack doing everything for them. Not every module is like that. You'll have to use some engineering skills to craft a useful, clever approach if you want to use this module. If that's not something you can do, there's always `webpack-dev-server` as a tried and true alternative. 

Before leveling harsh criticism because a module/package doesn't do what _you_ need it to for _your_ particular scenario, ask yourself: What would it take for me to write a module to do the same as the one I'm criticizing?

If the answer to that is _"not much"_, then sit down and crank it out! Or submit a PR! Or fork and make some magic! Any of those would be much more effective, and I challenge you to do something beyond a drive-by complaint.

**Comment by catamphetamine** [comment]
Screw your library, I'm making my own.
And your code can't even serve statics on a prefixed publicPath.
Your library is really silly and inconvenient.
