### ISSUE TITLE
Documentation: Content option explanation improvement

### ISSUE THREAD

**Issue by wzup** [webpack-contrib/webpack-serve#86]
* Operating System: `Ubuntu 16.04.3 LTS`
* Node Version: `v8.9.4`
* NPM Version: `5.6.0`
* webpack Version: `2.2.1`
* webpack-serve Version: `^0.3.0`

This issue is for a:

- [ ] **bug**
- [x] **modification** request
- [ ] **feature** request

### New Feature Use Case
Need more info on `content` option https://github.com/webpack-contrib/webpack-serve#content

**Comment by shellscape** [comment]
> The path, or array of paths, from which content will be served.

I must disagree that this is unclear. This is a basic feature of any webserver application, ever. What is unclear about this?

**Comment by lloydh** [comment]
I'm in agreement with wzup that the documentation would benefit from further explanation, and/or a usage or use-case example, especially since the option name '`content`' little insight.

I'm sure most users will be able to figure out how `content` works but an additional sentence or two for clarity would prevent any potential confusion, e.g. when might you specify multiple paths, how do they interact, etc.

As an aside, I'd question the assumption that users of webpack-serve should be familiar with server conventions. I think this project will naturally attract a lot of devs with mostly front-end experience.

**Comment by shellscape** [comment]
@lloydh I'm honestly not sure how more crystal clear that can be. A server serves content. That's its job, that's basic info. I'd happily review a pull request that contained additions or expansions (within reason) to the docs and README.

> As an aside, I'd question the assumption that users of webpack-serve should be familiar with server conventions. I think this project will naturally attract a lot of devs with mostly front-end experience.

I cannot abide the idea that tools should be so easy to use it requires zero knowledge from users. If one is wading into the arena of using a server, one should educate - and the location from where content for a site is served is the _most basic of settings_. When I first started using server applications, I had to learn and understand concepts like `wwwroot` (IIS) and `/var/www/html` (Apache+DocumentRoot) in order for me to effectively work as a front end engineer. There's no way to make this sound any less harsh - folks can't be lazy when they start using a new technology, and it's not the responsibility or job of tools to enable them to be. Tools are there for convenience and ease of use, to wrap harder sets of tasks, but they don't exist to excuse users from learning.

_That said, I would prefer no further delving into that tangent and for the thread to remain on topic with yours and @wzup's request for enhanced documentation._

I'm always open to expanding the documentation, so please submit a PR with the changes you feel would benefit users, and we'll have a look.

**Comment by wzup** [comment]
@shellscape 
> **content**
> _The path, or array of paths, from which content will be served._

Well, precisely I don't understand the following about `content` option.
What _path_ do you mean? Is _path_
1) a url path, like `foo/bar` below:
```
http://www.myapp.com/foo/bar
```
2) or a OS filesystem path, like examples below?
```
/home/user/app.com/dist/
/home/user/app.com/dist/index.html
/home/user/app.com/public/
/home/user/app.com/public/index.html
```

**Comment by shellscape** [comment]
> I'm always open to expanding the documentation, so please submit a PR with the changes you feel would benefit users, and we'll have a look.

Folks, I don't know how many other ways to say that. If you'd like to see that expanded, do the work and contribute.

**Comment by Glideh** [comment]
I admit I had to do some tests with the `content` setting in order to understand the behavior.
If I understand well, correct me if I'm wrong, it is the nginx `root` directive equivalent.
So every files located in this path will be served.
Since I love this project, I'll try to find some time and propose a PR.
