### ISSUE TITLE
Set webpack-serve server as webpack-hot-client server

### ISSUE THREAD

**Issue by MatTheCat** [webpack-contrib/webpack-serve#96]
* Operating System: Alpine 3.7
* Node Version: 8.9.3
* NPM Version: 5.5.1
* webpack Version: 4.4.1
* webpack-serve Version: 0.3.1

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

### New Feature Use Case

I don’t even know if my request makes sense but I would like to have *webpack-serve* and *webpack-hot-client* listen on one only port in order to ease their usage in Docker. I saw *webpack-hot-client* can take a `server` option, could this be *webpack-serve*’s server?

**Comment by shellscape** [comment]
@MatTheCat Thanks for the issue 🍺  Indeed, it's any instance of a [`http.Server`](https://nodejs.org/api/https.html#https_class_https_server) that has been instructed to begin listening.

**Comment by MatTheCat** [comment]
So do you think it would be possible to use *webpack-serve* server as *webpack-hot-client*’s? I guess this would require to update *webpack-serve*?

**Comment by shellscape** [comment]
That option just tells `ws` to listen on the same port and address as the server. It's not something we want to encourage with `webpack-serve` because there are complications with releasing the port and resources, and reliably terminating the process, when you have multiple services listening on the same port. It's simpler and easier to maintain with one-server-one-port. What I'd recommend is that you open a thorough issue on `webpack-hot-client` explaining your scenario in detail, and why it's needed, and the discussion around the merits of allowing the `ws` server to listen on a port in use can happen over there.

**Comment by MatTheCat** [comment]
Okay I understand. So what I did in my Dockerfile is to `EXPOSE` *webpack-serve*’s port and setting a `WEBPACK_HOT_PORT` environment variable. Then `docker create` will take

```bash
-e WEBPACK_HOT_PORT -p $WEBPACK_SERVE_PORT:8080 -p $WEBPACK_HOT_PORT:$WEBPACK_HOT_PORT
```

and *webpack-serve*’s config

```js
hot: {
    port: process.env.WEBPACK_HOT_PORT
}
```
