### ISSUE TITLE
If more than one connection, keeps refreshing

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/webpack-serve#98]
* Operating System: MacOS
* Node Version: 9.7.1
* NPM Version: 5.8.0
* webpack Version: 4.5.0
* webpack-serve Version: 0.3.1

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code

https://github.com/bebraw/webpack-serve-crash

### Expected Behavior

Should not keep refreshing tabs.

### Actual Behavior

Keeps refreshing tabs.

### How Do We Reproduce?

Run the repo above.

**Comment by csvn** [comment]
![infinite-reload-webpack-serve](https://user-images.githubusercontent.com/8770194/38511698-387a47b6-3c29-11e8-858e-304c681385d5.gif)

I have the same issue. Seems that `webpack-serve` sends out responses to all clients whenever one connects, which makes the tabs reload back and forth:

1. Browser X connects:
  ![image](https://user-images.githubusercontent.com/8770194/38511759-716e0d64-3c29-11e8-8329-f87587269c71.png)
2. Browser Y connects (same as above)
3. Browser X gets duplicated socket frames when browser Y connects
  ![image](https://user-images.githubusercontent.com/8770194/38511828-af7e61ee-3c29-11e8-8286-60eaacf51429.png)
4. Browser X reloads
5. Continue from step 2) where X and Y trade places

This makes it real hard to effectively use multiple devices for testing.

**Comment by csvn** [comment]
I looked into this a bit, and I think this occurs because of `webpack-hot-client`. It uses a method `sendStats`, which [broadcasts to all connected clients each time on client connects](https://github.com/webpack-contrib/webpack-hot-client/blob/0d8707da129cdb6d9b892603c330f4dd2eac829f/index.js#L171).

This in turn reaches the client which will [reload if a sent request is not the "first" one](https://github.com/webpack-contrib/webpack-hot-client/blob/0d8707da129cdb6d9b892603c330f4dd2eac829f/lib/client/index.js#L64-L71). I am not sure what's done differently in `webpack-dev-server` (is `webpack-hot-client` in use there?) or how best to do a PR for this.

**Comment by shellscape** [comment]
This is really a `webpack-hot-client` issue but we can triage it here since this is the primary consumer of the module at the moment. `webpack-dev-server` is a completely different platform and it's to put any thought of similarity of parity in cause between the two projects.

I didn't consider multiple tabs when writing hot-client, and the only multiple client socket tests that are run aren't in the browser, so it's something that's going to need to be examined. There might not be a reason to notify other sockets on a new socket connection, but we'd need to verify that thoroughly. I do believe that this part was modeled off of webpack-hot-middleware at the time.

**Comment by ematipico** [comment]
I have encountered the same issue but on a total different scenarios that I can describe.

**First scenario - multiple entry points**
I had an application where I was generating two entry points (vendors and app) and when running the server, it was keeping refreshing the application. By removing the `<script>` tag of one of the two entry points, everything was fine. I ended up by merging the two entry points in one single file (for development is fine)

**Second scenario - multiple configuration and iframe**
This is scenario is actually rare but maybe it could give some hints. I basically give to webpack and array of configurations. Both of them returns **one single entry point, so one file each**. Now, I bootstrap the application and I import one of the two files. Later on, there's an iframe that imports the second file. The moment gets imported, there's a refresh of the page.

I think I will dodge the issue by creating two different servers, one for each configuration. Although, I am pretty sure that with `webpack-dev-server` I was able to have multiple entry points loaded without problems

**Comment by ematipico** [comment]
@shellscape is there some room of help here? I could land some help if you can point me into the right direction. I am trying to build the dev server using this library but at the moment I am quite stuck. Having two servers doesn't solve my issue.

**Comment by shellscape** [comment]
@ematipico the triage by @csvn pretty much nails it, and there's more info in my comment following theirs. This is on my list to tackle as soon as I get done with another webpack project currently in development (which is nearly ready).

**Comment by shellscape** [comment]
This was resolved in `webpack-hot-client` v3.0.0, and will be available to `webpack-serve` on the next release. (soon)
